### ISSUE TITLE
Prevent the user to select text on menus or buttons.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#213]
Prevent the user to select text on menus or buttons.

The following style could prevent the user to select the text on our buttons and menus. These may make Kahla looks more native.

```css
.disHighlight{
    user-select: none;
    -webkit-user-select: none;
    -ms-user-select: none;
    -webkit-touch-callout: none;
    -o-user-select: none;
    -moz-user-select: none;
}
```

https://stackoverflow.com/questions/2326004/prevent-selection-in-html
