### ISSUE TITLE
[Question] About the Azure pipelines

### ISSUE THREAD

**Issue by ghost** [AiursoftWeb/Kahla#689]
## What do you want to know?

1. How do you hide the Azure pipelines file?
2. How do you build 2 and more platforms in Azure pipelines in the same time?

## Describe alternatives you've considered

I have to...

Use one or more AppPools?
Use More tasks?

## Additional context

Nothing.

**Comment by Anduin2017** [comment]
Hi, here is our pipeline configuration:

Build pipeline Kahla.App Check:

```yaml
pool:
  name: Hosted Ubuntu 1604
steps:
- task: NodeTool@0
  displayName: 'Use Node 11.x'
  inputs:
    versionSpec: 11.x
    checkLatest: true

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm lint'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run lint'

- bash: |
   echo git branch
   currentBranch=$(Build.SourceBranch)
   echo Current branch is: $currentBranch
   if [ "$currentBranch" == "refs/heads/master" ]; then
      serverAddress="https://server.kahla.app"
   else
      serverAddress="https://staging.server.kahla.app"
   fi
   
   echo Using server Address: $serverAddress
   
   json="export const environment = { production: true, server: '$serverAddress', applicationServerKey: 'BJOTNmtE1V5GyDiYtoUzWbWLiaVMyfdnXFTvneJCbi9mwpw7FAVgQgIR9JN43TWkpT7ezBes1fPYr4nPqV6qXA0' };"
   
   echo Writting JSON: \"$json\"
   echo $json > ./src/environments/environment.prod.ts
   
   if [ "$currentBranch" == "refs/heads/master" ]; then
      echo 'building production PWA App'
   else
      sed -i  "s/Kahla/Kahla Staging/g" ./src/manifest.json
   fi
   
   
  displayName: 'Generate Server Config'

- task: Npm@1
  displayName: 'npm prod'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run prod'
```

Kahla.App Build:

Web Build:

```yaml
pool:
  name: Hosted Ubuntu 1604
steps:
- task: NodeTool@0
  displayName: 'Use Node 12.x'
  inputs:
    versionSpec: 12.x
    checkLatest: true

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm lint'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run lint'

- bash: |
   echo git branch
   currentBranch=$(Build.SourceBranch)
   echo Current branch is: $currentBranch
   if [ "$currentBranch" == "refs/heads/master" ]; then
      serverAddress="https://server.kahla.app"
   else
      serverAddress="https://staging.server.kahla.app"
   fi
   
   echo Using server Address: $serverAddress
   
   json="export const environment = { production: true, server: '$serverAddress', applicationServerKey: '<-Hidden Key->' };"
   
   echo Writting JSON: \"$json\"
   echo $json > ./src/environments/environment.prod.ts
   
   if [ "$currentBranch" == "refs/heads/master" ]; then
      echo 'building production PWA App'
   else
      sed -i  "s/Kahla/Kahla Staging/g" ./src/manifest.json
   fi
   
   
  displayName: 'Generate Server Config'

- task: Npm@1
  displayName: 'npm prod'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run prod'

- task: ArchiveFiles@2
  displayName: Archive
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/www'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/web.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Kahla Web'
  inputs:
    ArtifactName: KahlaWeb
```

Electron build:

```yaml
pool:
  name: Hosted Windows Container
steps:
- bash: |
   echo git branch
   currentBranch=$(Build.SourceBranch)
   echo Current branch is: $currentBranch
   if [ "$currentBranch" == "refs/heads/master" ]; then
      serverAddress="https://server.kahla.app"
   else
      serverAddress="https://staging.server.kahla.app"
   fi
   
   echo Using server Address: $serverAddress
   
   json="export const environment = { production: true, server: '$serverAddress', applicationServerKey: '<--Hidden key-->' };"
   
   echo Writting JSON: \"$json\"
   echo $json > ./src/environments/environment.prod.ts
  displayName: 'Generate Server Config'

- task: NodeTool@0
  displayName: 'Use Node 12.x'
  inputs:
    versionSpec: 12.x
    checkLatest: true

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Bash@3
  displayName: 'Build Electron'
  inputs:
    targetType: filePath
    filePath: ./publish.sh

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: KahlaWindows'
  inputs:
    PathtoPublish: dist
    ArtifactName: KahlaWindows

```

And for our publish script:

```bash
#!/bin/bash

# clean all built assets.
rm -rvf ./www/
rm -rvf ./dist/
npm run prod-electron

# generate package.json without dependencies.
cp ./package.json ./www/
if [[ "$OSTYPE" == "darwin"* ]]
then
    sed -i '' '6,$d' ./www/package.json
else
    sed -i '6,$d' ./www/package.json
fi
echo '  "main": "index.js"' >> ./www/package.json
echo '}' >> ./www/package.json

# call electron builder without publishing anything.
npx electron-builder -p never

# cp package.json so that release server could read version number.
cp ./package.json ./dist/

# remove additional useless files

rm -rvf ./dist/win-unpacked
rm -rvf ./dist/linux-unpacked
rm -rvf ./dist/mac
```

Hope that helps you.
